// Dear emacs, this is -*-c++-*-
#ifndef CxAODTools_CommonProperties_H
#define CxAODTools_CommonProperties_H

#ifndef __MAKECINT__

#include "xAODJet/Jet.h"

#include "CxAODTools/ObjectDecorator.h"


// Preprocessor macro to define property classes
//
// Usage example:
// (in ~ CxAODTools_MyAnalysis/CxAODTools_MyAnalysis/Properties_MyAnalysis.h)
//
// #include "CxAODTools/CommonProperties.h"
// PROPERTY( Props , int   , myInt   );
// PROPERTY( Props , float , myFloat );
// PROPERTY( MyProps , int   , myInt   );
// ...

// For faster compile times the declaration and instantiation can be split.
// E.g. in Properties_MyAnalysis.h:
// PROPERTY_DECL( Props , int   , myInt   );
// And in Properties_MyAnalysis.cxx:
// PROPERTY_INST( Props , int   , myInt   );

// Note, it is _never_ needed to specify your own namespace "MyProps" if the
// property already exists in another namespace, e.g. in "Props". In general,
// it's better always use namespace "Props" in your own analysis, since you
// then get an extra compile time check on whether you declared a property
// with the same name as another previously declared property but with a
// different type (if using a different namespace, this would compile, but
// fail at runtime).

// IMPORTANT :
// Don't attempt use bool properties !!!
// A bool properties gets saved as char when written to disk.
// Consequently, you cannot use the same code to access the property, when
// reading the file back in. For this reason, the bool template is disabled.


// OR tool
PROPERTY_DECL( Props , char , ORInputLabel )
PROPERTY_DECL( Props , char , OROutputLabel )
PROPERTY_DECL( Props , char , LepOnlyORInputLabel )
PROPERTY_DECL( Props , char , LepOnlyOROutputLabel )
PROPERTY_DECL( Props , char , hasSharedTrack )

// common stuff
PROPERTY_DECL( Props , int , passPreSel )
PROPERTY_DECL( Props , int , passSel )
PROPERTY_DECL( Props , int , passMJSel )
PROPERTY_DECL( Props , int , partIndex )
PROPERTY_DECL( Props , char, passOR )
PROPERTY_DECL( Props , char, passLepOnlyOR )
PROPERTY_DECL( Props , int , passVarOR )   //New Variable Muon-trackJet OverlapRemoval
PROPERTY_DECL( Props , int , passORGlob )
PROPERTY_DECL( Props , int , forMETRebuild )

// 4-vector components
PROPERTY_DECL( Props, float, pt)
PROPERTY_DECL( Props, float, eta)
PROPERTY_DECL( Props, float, phi)
PROPERTY_DECL( Props, float, m)

// MET soft term components
PROPERTY_DECL( Props, float, soft_mpx )
PROPERTY_DECL( Props, float, soft_mpy )
PROPERTY_DECL( Props, float, soft_sumet )
// MET significance
PROPERTY_DECL( Props, float, metSig ) // MET significance using object pT resolutions using data resolution for jets
PROPERTY_DECL( Props, float, metSig_PU ) // MET significance using object pT resolutions using data resolution for jets and pileup corrections
PROPERTY_DECL( Props, float, metSig_soft ) // MET significance using object pT resolutions using data resolution for jets rotated in the soft directions
PROPERTY_DECL( Props, float, metSig_hard ) // MET significance using object pT resolutions using data resolution for jets rotated in the hard object direction
PROPERTY_DECL( Props, float, metSig_old_reco ) // MET significance using object pT resolutions using data resolution for jets
PROPERTY_DECL( Props, float, metSig_phireso ) // MET significance using object pT resolutions using data resolution for jets
PROPERTY_DECL( Props, float, metOverSqrtSumET ) // MET/sqrt(SumET) using the MET computation of sumET
PROPERTY_DECL( Props, float, metOverSqrtHT ) // MET computation of sumET without the soft term sumET
PROPERTY_DECL( Props, float, metDirectional ) // MET / resolution in the direction of the MET only
PROPERTY_DECL( Props, float, metRho ) // rho
PROPERTY_DECL( Props, float, metVarL ) // resolution in the direction of the MET only
PROPERTY_DECL( Props, float, metVarL_soft ) // resolution in the direction of the MET only calculated in the soft term direction
PROPERTY_DECL( Props, float, metVarL_hard ) // resolution in the direction of the MET only calculated in the hard object direction
PROPERTY_DECL( Props, float, metVarT ) // resolution perpendicular to the MET
// Isolation working poins under test
PROPERTY_DECL( Props, int, isFixedCutTightCaloOnlyIso) //photon iso
PROPERTY_DECL( Props, int, isFixedCutHighPtCaloOnlyIso) //electron iso
PROPERTY_DECL( Props, int, isGradientIso) //electron iso
PROPERTY_DECL( Props, int, isFixedCutTightIso) //electron + muon iso
PROPERTY_DECL( Props, int, isFixedCutLooseIso) //electron + muon iso
PROPERTY_DECL( Props, int, isFixedCutTightFixedRadIso) //electron + muon iso under test
PROPERTY_DECL( Props, int, isFixedCutLooseFixedRadIso) //electron + muon iso under test
PROPERTY_DECL( Props, int, isLooseTrackOnlyIso) //electron + muon iso (not supported)
PROPERTY_DECL( Props, int, isFCTightTrackOnly_FixedRadIso) //muon iso
PROPERTY_DECL( Props, int, isFCLoose_FixedRadIso) //muon iso
PROPERTY_DECL( Props, int, isFCTight_FixedRadIso) //muon iso
PROPERTY_DECL( Props, int, isFixedCutHighPtTrackOnlyIso) //muon iso
PROPERTY_DECL( Props, int, isFixedCutTightTrackOnlyIso) //muon iso (not supported)
PROPERTY_DECL( Props, int, isFixedCutPflowTightIso) // muon iso
PROPERTY_DECL( Props, int, isFixedCutPflowLooseIso) // muon iso

//Implementation of the corresponding SF muon
PROPERTY_DECL( Props, float, looseTrackOnlyIsoSF)
PROPERTY_DECL( Props, float, fCTightTrackOnly_FixedRadIsoSF)
PROPERTY_DECL( Props, float, fCLoose_FixedRadIsoSF)
PROPERTY_DECL( Props, float, fCTight_FixedRadIsoSF)
PROPERTY_DECL( Props, float, fixedCutHighPtTrackOnlyIsoSF)
PROPERTY_DECL( Props, float, fixedCutTightTrackOnlyIsoSF)
PROPERTY_DECL( Props, float, fixedCutLooseIsoSF)
PROPERTY_DECL( Props, float, fixedCutTightIsoSF)
PROPERTY_DECL( Props, float, fixedCutPflowTightIsoSF)
PROPERTY_DECL( Props, float, fixedCutPflowLooseIsoSF)

//Trigger SF to be improved
PROPERTY_DECL( Props, float, trigSF)

// b-tagging
PROPERTY_DECL( BTagProps , float , eff )
PROPERTY_DECL( BTagProps , float , SF )
PROPERTY_DECL( BTagProps , float , tagWeight )
PROPERTY_DECL( BTagProps , int , Quantile )
PROPERTY_DECL( BTagProps , int , isTagged )
PROPERTY_DECL( BTagProps , float , truthTagEventWeight )
PROPERTY_DECL( Props , const xAOD::Jet* , GAFatJet )
PROPERTY_DECL( Props , int , isBJet )
PROPERTY_DECL( Props , char , isBTag )

//ditau mass
PROPERTY_DECL( Props , int , mmc_fit_status)
PROPERTY_DECL( Props , double , mmc_maxw_mass)
PROPERTY_DECL( Props , double , mmc_mlm_mass)
PROPERTY_DECL( Props , double , mmc_mlnu3p_mass)
PROPERTY_DECL( Props , TLorentzVector , mmc_mlnu3p_4vect)
PROPERTY_DECL( Props , double , mmc_mlnu3p_4vect_pt)
PROPERTY_DECL( Props , double , mmc_mlnu3p_4vect_eta)
PROPERTY_DECL( Props , double , mmc_mlnu3p_4vect_phi)
PROPERTY_DECL( Props , double , mmc_mlnu3p_4vect_m)

// e-gamma ID
PROPERTY_DECL( Props , int , isVeryLooseLH )
PROPERTY_DECL( Props , int , isLooseNoBLLH )
PROPERTY_DECL( Props , int , isLooseLH )
PROPERTY_DECL( Props , int , isMediumLH )
PROPERTY_DECL( Props , int , isTightLH )
PROPERTY_DECL( Props , int , isTightPP )
PROPERTY_DECL( Props , int , isMediumPP )
PROPERTY_DECL( Props , int , isLoosePP )
PROPERTY_DECL( Props , float , ElClusterEta )
PROPERTY_DECL( Props , float , PromptLeptonVetoEl )
PROPERTY_DECL( Props , float , PromptLeptonIsoEl )
PROPERTY_DECL( Props , float , LHValue )

PROPERTY_DECL( Props, float, TTVAEffSF )
PROPERTY_DECL( Props, double, highPtEffSF )// from MuonHandler.cxx
PROPERTY_DECL( Props, double, lowPtEffSF )// from MuonHandler.cxx
PROPERTY_DECL( Props, double, tightEffSF )
PROPERTY_DECL( Props, double, mediumEffSF )
PROPERTY_DECL( Props, double, looseEffSF )
PROPERTY_DECL( Props, double, photonFixedCutTightEffSF )
PROPERTY_DECL( Props, double, photonFixedCutLooseEffSF )


// analysis quality assignment
PROPERTY_DECL( Props , int , isVHLooseElectron )
PROPERTY_DECL( Props , int , isVHSignalElectron )
PROPERTY_DECL( Props , int , isZHSignalElectron )
PROPERTY_DECL( Props , int , isWHSignalElectron )
PROPERTY_DECL( Props , int , isTTLHOLRElectron )
PROPERTY_DECL( Props , int , isTTLHDiLepVetoElectron )
PROPERTY_DECL( Props , int , isTTLHPreSelElectron )
PROPERTY_DECL( Props , int , isTTLHIsolElectron )
PROPERTY_DECL( Props , int , isTTLHSoftElectron )
PROPERTY_DECL( Props , int , isEWOrigin )

//VV
PROPERTY_DECL( Props , int , isVVLooseElectron )
PROPERTY_DECL( Props , int , isVVTightElectron )

//HH->bbtautau
PROPERTY_DECL( Props , int , tauTJVAIndex)
PROPERTY_DECL( Props , int , isBBTTSignalElectron )
PROPERTY_DECL( Props , int , isBBTTLLSignalElectron )
PROPERTY_DECL( Props , int , isHHLooseElectron )
PROPERTY_DECL( Props , int , isAntiTau )
PROPERTY_DECL( Props , float , BDTCut )
PROPERTY_DECL( Props , float , TauORJetPt )
PROPERTY_DECL( Props , float , TauORJetEta )
PROPERTY_DECL( Props , float , TauORJetPhi )
PROPERTY_DECL( Props , float , TauORJetE )
PROPERTY_DECL( Props , float , TauORJetDR )
PROPERTY_DECL( Props , int , isDiTauJet )
PROPERTY_DECL( Props , int , isForHadHad )
PROPERTY_DECL( Props , int , isForFourTauOnly )

// HWW maybe?
PROPERTY_DECL( Props , int , isHWWLooseElectron )
PROPERTY_DECL( Props , int , isHWWSignalElectron )
PROPERTY_DECL( Props , int , isHWWLooseMuon )
PROPERTY_DECL( Props , int , isHWWSignalMuon )

PROPERTY_DECL( Props , float , effSFloose )
PROPERTY_DECL( Props , float , effSFlooseLH )
PROPERTY_DECL( Props , float , effSFmediumLH )
PROPERTY_DECL( Props , float , effSFtightLH )
PROPERTY_DECL( Props , float , effSFReco )
PROPERTY_DECL( Props , float , effSFtight )
PROPERTY_DECL( Props , float , trigSFlooseLH )
PROPERTY_DECL( Props , float , trigSFmediumLH )
PROPERTY_DECL( Props , float , trigSFtightLH )
PROPERTY_DECL( Props , float , trigSFlooseLHIsoFixedCutLoose ) //required by VHbb
PROPERTY_DECL( Props , float , trigEFFlooseLHIsoFixedCutLoose ) //required by VHbb
PROPERTY_DECL( Props , float , trigSFlooseLHIsoLooseTrackOnly ) //deprecated but still under test
PROPERTY_DECL( Props , float , trigEFFlooseLHIsoLooseTrackOnly ) //deprecated but still under test
PROPERTY_DECL( Props , float , trigSFtightLHIsoFixedCutTight ) //required by VHbb
PROPERTY_DECL( Props , float , trigEFFtightLHIsoFixedCutTight ) //required by VHbb
PROPERTY_DECL( Props , float , trigSFtightLHIsoFixedCutLoose )//required by bbtautau
PROPERTY_DECL( Props , float , trigEFFtightLHIsoFixedCutLoose )//required by bbtauta
PROPERTY_DECL( Props , float , e17trigSFmediumLHIsoFixedCutLoose )//required by bbtautau
PROPERTY_DECL( Props , float , e17trigEFFmediumLHIsoFixedCutLoose )//required by bbtautau
PROPERTY_DECL( Props , float , trigSFmediumLH_offTightIsoFixedCutLoose )//required by bbtautau
PROPERTY_DECL( Props , float , trigEFFmediumLH_offTightIsoFixedCutLoose )//required by bbtautau
PROPERTY_DECL( Props , int   , triggerMatched )

//
PROPERTY_DECL( Props , float , trigSF_mu )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu20_iloose_L1MU15 )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu24_iloose_L1MU15 )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu24_imedium )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu26_imedium )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu24_ivarmedium )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu26_ivarmedium )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu50 )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu20_iloose_L1MU15_OR_HLT_mu50 )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu24_iloose_L1MU15_OR_HLT_mu50 )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu24_imedium_OR_HLT_mu50 )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu26_imedium_OR_HLT_mu50 )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu24_ivarmedium_OR_HLT_mu50 )
PROPERTY_DECL( Props , float , trigSF_mu_HLT_mu26_ivarmedium_OR_HLT_mu50 )

PROPERTY_DECL( Props, float, effSFIsoGradientLooseLH)
PROPERTY_DECL( Props, float, effSFIsoGradientMediumLH)
PROPERTY_DECL( Props, float, effSFIsoGradientTightLH)
PROPERTY_DECL( Props, float, effSFIsoFixedCutLooseLooseLH)
PROPERTY_DECL( Props, float, effSFIsoFixedCutLooseMediumLH)
PROPERTY_DECL( Props, float, effSFIsoFixedCutLooseTightLH)
PROPERTY_DECL( Props, float, effSFIsoFixedCutTightLooseLH)
PROPERTY_DECL( Props, float, effSFIsoFixedCutTightMediumLH)
PROPERTY_DECL( Props, float, effSFIsoFixedCutTightTightLH)
PROPERTY_DECL( Props, float, effSFIsoFixedCutHighPtCaloOnlyLooseLH)
PROPERTY_DECL( Props, float, effSFIsoFixedCutHighPtCaloOnlyMediumLH)
PROPERTY_DECL( Props, float, effSFIsoFixedCutHighPtCaloOnlyTightLH)
PROPERTY_DECL( Props, float, effSFIsoLooseTrackOnlyLooseLH)  //Deprecated
PROPERTY_DECL( Props, float, effSFIsoLooseTrackOnlyMediumLH) //Deprecated
PROPERTY_DECL( Props, float, effSFIsoLooseTrackOnlyTightLH)  //Deprecated

PROPERTY_DECL( Props , float , charge )
PROPERTY_DECL( Props , float , resolution )

PROPERTY_DECL( Props , int , passedIDCuts )
PROPERTY_DECL( Props , int , acceptedMuonTool )
PROPERTY_DECL( Props , int , muonQuality )
PROPERTY_DECL( Props , int , isVHLooseMuon )
PROPERTY_DECL( Props , int , isVHSignalMuon )
PROPERTY_DECL( Props , int , isZHSignalMuon )
PROPERTY_DECL( Props , int , isWHSignalMuon )
PROPERTY_DECL( Props , int , isTTLHOLRTauMuon )
PROPERTY_DECL( Props , int , isTTLHDiLepVetoMuon )
PROPERTY_DECL( Props , int , isTTLHPreSelMuon )
PROPERTY_DECL( Props , int , isTTLHIsolMuon )
PROPERTY_DECL( Props , int , isTTLHSoftMuon )
PROPERTY_DECL( Props , int , isVVLooseMuon )

PROPERTY_DECL( Props , float , PromptLeptonIsoMuon )
PROPERTY_DECL( Props , float , PromptLeptonVetoMuon )

PROPERTY_DECL( Props , float , reducedChi2 )
PROPERTY_DECL( Props , float , qOverPsignif )

//HH->bbtautau
PROPERTY_DECL( Props , int , isBBTTSignalMuon )
PROPERTY_DECL( Props , int , isBBTTLLSignalMuon )
PROPERTY_DECL( Props , int , isHHLooseMuon )

PROPERTY_DECL( Props , float , z0 )
PROPERTY_DECL( Props , float , z0sinTheta )
PROPERTY_DECL( Props , float , z0sigBL )
PROPERTY_DECL( Props , float , d0 )
PROPERTY_DECL( Props , float , d0sig )
PROPERTY_DECL( Props , float , d0sigBL )

PROPERTY_DECL( Props , float , z0_ID )
PROPERTY_DECL( Props , float , z0sinTheta_ID )
PROPERTY_DECL( Props , float , z0sigBL_ID )
PROPERTY_DECL( Props , float , d0_ID )
PROPERTY_DECL( Props , float , d0sig_ID )
PROPERTY_DECL( Props , float , d0sigBL_ID )

PROPERTY_DECL( Props, float , innerTrackPt )
PROPERTY_DECL( Props, float , innerTrackEta )
PROPERTY_DECL( Props, float , innerTrackPhi )
PROPERTY_DECL( Props , float , effSF)
PROPERTY_DECL( Props , float , tauSF)

// These properties are deprecated but might be needed for release
// r32-16 and earlier. Use effSFtrigger instead.
PROPERTY_DECL( Props , float , effSFtriggerMedium25 )
PROPERTY_DECL( Props , float , effSFtriggerMedium35 )
PROPERTY_DECL( Props , float , effSFtriggerMedium80 )
PROPERTY_DECL( Props , float , effSFtriggerMedium125 )
PROPERTY_DECL( Props , float , effSFtriggerMedium160 )
PROPERTY_DECL( Props , float , effSFtriggerLoose25 )
PROPERTY_DECL( Props , float , effSFtriggerLoose35 )
PROPERTY_DECL( Props , float , effSFtriggerLoose80 )
PROPERTY_DECL( Props , float , effSFtriggerLoose125 )
PROPERTY_DECL( Props , float , effSFtriggerLoose160 )

PROPERTY_DECL( Props , float , effSFtrigger25 )
PROPERTY_DECL( Props , float , effSFtrigger35 )
PROPERTY_DECL( Props , float , effSFtrigger80 )
PROPERTY_DECL( Props , float , effSFtrigger125 )
PROPERTY_DECL( Props , float , effSFtrigger160 )

PROPERTY_DECL( Props , float , MV1 )
PROPERTY_DECL( Props , float , SV1_IP3D )
PROPERTY_DECL( Props , int   , isVBF)
PROPERTY_DECL( Props , float , MV2c00 )
PROPERTY_DECL( Props , float , MV2c10 )
PROPERTY_DECL( Props , float , MV2c20 )
PROPERTY_DECL( Props , float , MV2c100 )
PROPERTY_DECL( Props , float , MV2cl100 )
PROPERTY_DECL( Props , float , MVb )
PROPERTY_DECL( Props , float , MV2c10mu )
PROPERTY_DECL( Props , float , MV2c10rnn )
PROPERTY_DECL( Props , double , DL1_pb )
PROPERTY_DECL( Props , double , DL1_pc )
PROPERTY_DECL( Props , double , DL1_pu )
PROPERTY_DECL( Props , double , DL1mu_pb )
PROPERTY_DECL( Props , double , DL1mu_pc )
PROPERTY_DECL( Props , double , DL1mu_pu )
PROPERTY_DECL( Props , double , DL1rnn_pb )
PROPERTY_DECL( Props , double , DL1rnn_pc )
PROPERTY_DECL( Props , double , DL1rnn_pu )
PROPERTY_DECL( Props , double , DL1r_pb )
PROPERTY_DECL( Props , double , DL1r_pc )
PROPERTY_DECL( Props , double , DL1r_pu )
PROPERTY_DECL( Props , float , RhoEventShape )
PROPERTY_DECL( Props , float , Jvt )
PROPERTY_DECL( Props , float , EMScaleEta )
PROPERTY_DECL( Props , float , DetectorEta )
PROPERTY_DECL( Props , int , PassJvtMedium )
PROPERTY_DECL( Props , float , JvtSF )
PROPERTY_DECL( Props , float , FJvt )
PROPERTY_DECL( Props , int , PassFJvtTight )
PROPERTY_DECL( Props , int , PassFJvtLoose )
PROPERTY_DECL( Props , float , FJvtSF )
PROPERTY_DECL( Props , float , QGTagger )
PROPERTY_DECL( Props , int , QGTag_result )
PROPERTY_DECL( Props , float , QGTaggerWeight )
PROPERTY_DECL( Props , char , PassFJVTMET )
PROPERTY_DECL( Props , float , TrackWidthPt1000PV )
PROPERTY_DECL( Props , float , TrackWidthPt500PV )
PROPERTY_DECL( Props , int , NumTrkPt1000PV )
PROPERTY_DECL( Props , int , NumTrkPt500PV )
PROPERTY_DECL( Props , float , SumPtTrkPt500PV )
PROPERTY_DECL( Props , int , DFCommonJets_QGTagger_NTracks )
PROPERTY_DECL( Props , float , DFCommonJets_QGTagger_TracksWidth )
PROPERTY_DECL( Props , float , DFCommonJets_QGTagger_TracksC1 )
PROPERTY_DECL( Props , float , Width )
PROPERTY_DECL( Props , float , ConstPx )
PROPERTY_DECL( Props , float , ConstPy )
PROPERTY_DECL( Props , float , ConstPz )


PROPERTY_DECL( Props , int , goodJet )
PROPERTY_DECL( Props , char , DFCommonJets_jetClean_LooseBad ) //r21 new Jet cleaning recommendation
PROPERTY_DECL( Props , char , DFCommonJets_jetClean_TightBad ) //r21 new Jet cleaning recommendation
PROPERTY_DECL( Props , float , Timing )
PROPERTY_DECL( Props , int , TruthLabelID )     //rel19
PROPERTY_DECL( Props , int , ConeTruthLabelID ) //rel20
PROPERTY_DECL( Props , int , TruthPartonLabelID )     //rel21
PROPERTY_DECL( Props , int , PartonTruthLabelID )     //Natasha
PROPERTY_DECL( Props , float , truthjet_eta )     //Natasha
PROPERTY_DECL( Props , float , truthjet_pt )     //Natasha
PROPERTY_DECL( Props , int , truthjet_nCharged )     //Natasha
PROPERTY_DECL( Props , int , truthjet_pdgid )     //Natasha
PROPERTY_DECL( Props , float , truthjet_deltaR )     //Natasha
PROPERTY_DECL( Props , int , nTruthjets )     //Natasha
PROPERTY_DECL( Props , float , qgweight_me_up )     //Natasha
PROPERTY_DECL( Props , float , qgweight_me_down )     //Natasha
PROPERTY_DECL( Props , float , qgweight_pdf_up )     //Natasha
PROPERTY_DECL( Props , float , qgweight_pdf_down )     //Natasha
PROPERTY_DECL( Props , float , qgweight_exp_up )     //Natasha
PROPERTY_DECL( Props , float , qgweight_exp_down )     //Natasha
PROPERTY_DECL( Props , float , qgweight_fake )     //Natasha
PROPERTY_DECL( Props , float , qgweight_trackeff )     //Natasha
PROPERTY_DECL( Props , float , qgweight_topo )     //Natasha
PROPERTY_DECL( Props , int , numConstituents )     //Natasha
PROPERTY_DECL( Props , int , TruthWZ_PartonTruthLabelID )     //Natasha
PROPERTY_DECL( Props , int , TruthWZ_numConstituents )     //Natasha
PROPERTY_DECL( Props , int , HadronConeExclTruthLabelID )
PROPERTY_DECL( Props , int , isVetoJet )
PROPERTY_DECL( Props , int , isSignalJet )

//semileptonic jet decays
//muon
PROPERTY_DECL( Props , int ,   nrMuonInJet )
PROPERTY_DECL( Props , int ,   nrMuonInJet04 )
//PROPERTY_DECL( Props , float , PtRatioOneMuonInJet )
//PROPERTY_DECL( Props , float , ERatioOneMuonInJet )
//PROPERTY_DECL( Props , float , PtRatioAllMuonInJet )
//PROPERTY_DECL( Props , float , ERatioAllMuonInJet )
//electron
PROPERTY_DECL( Props , int ,   nrElectronInJet )
PROPERTY_DECL( Props , int ,   nrElectronInJet04 )
//PROPERTY_DECL( Props , float , PtRatioOneElectronInJet )
//PROPERTY_DECL( Props , float , ERatioOneElectronInJet )
//PROPERTY_DECL( Props , float , PtRatioAllElectronInJet )
//PROPERTY_DECL( Props , float , ERatioAllElectronInJet )
//PtReco
PROPERTY_DECL( Props , float , factorPtReco )

//regression
PROPERTY_DECL( Props , float , factorRegression )
PROPERTY_DECL( Props , float , ptCorr )
PROPERTY_DECL( Props , float , RegInputEmscalePt )
PROPERTY_DECL( Props , float , RegInputNTrks )
PROPERTY_DECL( Props , float , RegInputLeadTrkPt )
PROPERTY_DECL( Props , float , RegInputSumTrkPt )
PROPERTY_DECL( Props , float , RegInputEtaWidthTrks )
PROPERTY_DECL( Props , float , RegInputPhiWidthTrks )
PROPERTY_DECL( Props , float , RegInputMuInJetPt )
PROPERTY_DECL( Props , float , RegInputElInJetPt )
PROPERTY_DECL( Props , float , RegInputDRJetLepInJet )
PROPERTY_DECL( Props , float , RegInputSumPtLeps )
PROPERTY_DECL( Props , float , RegInputSumPtCloseByJets )
PROPERTY_DECL( Props , float , RegInputSecVtxMass )
PROPERTY_DECL( Props , float , RegInputSecVtxNormDist )

// fatjet
PROPERTY_DECL( Props , int , passSubstructure )
PROPERTY_DECL( Props , int , passSubstructure50 )
PROPERTY_DECL( Props , int , passSubstructure80 )
PROPERTY_DECL( Props , int , passWSubstructure )
PROPERTY_DECL( Props , int , passWSubstructure50 )
PROPERTY_DECL( Props , int , passWSubstructure80 )
PROPERTY_DECL( Props , int , passZSubstructure )
PROPERTY_DECL( Props , int , passZSubstructure50 )
PROPERTY_DECL( Props , int , passZSubstructure80 )
PROPERTY_DECL( Props , int , passNtrk50 )
PROPERTY_DECL( Props , int , passNtrk80 )
PROPERTY_DECL( Props , int , passWNtrk50 )
PROPERTY_DECL( Props , int , passWNtrk80 )
PROPERTY_DECL( Props , int , passZNtrk50 )
PROPERTY_DECL( Props , int , passZNtrk80 )
PROPERTY_DECL( Props , int , FatjetTruthLabel )
PROPERTY_DECL( Props , int , passWMassCut )
PROPERTY_DECL( Props , int , passWMassCut50 )
PROPERTY_DECL( Props , int , passWMassCut80 )
PROPERTY_DECL( Props , int , passZMassCut )
PROPERTY_DECL( Props , int , passZMassCut50 )
PROPERTY_DECL( Props , int , passZMassCut80 )
PROPERTY_DECL( Props , int , passWHighMassCut50)
PROPERTY_DECL( Props , int , passWHighMassCut80)
PROPERTY_DECL( Props , int , passZHighMassCut50)
PROPERTY_DECL( Props , int , passZHighMassCut80)
PROPERTY_DECL( Props , int , passWLowMassCut50)
PROPERTY_DECL( Props , int , passWLowMassCut80)
PROPERTY_DECL( Props , int , passZLowMassCut50)
PROPERTY_DECL( Props , int , passZLowMassCut80)
PROPERTY_DECL( Props , int , passHMassCut )
PROPERTY_DECL( Props , int , isFatJet )
PROPERTY_DECL( Props , int , isIsoFatJet )
PROPERTY_DECL( Props , int , isWJet )
PROPERTY_DECL( Props , int , isWJet50 )
PROPERTY_DECL( Props , int , isWJet80 )
PROPERTY_DECL( Props , int , isHJet )
PROPERTY_DECL( Props , int , isZJet )
PROPERTY_DECL( Props , int , isZJet50 )
PROPERTY_DECL( Props , int , isZJet80 )

// definition for TCC, 2var selection (D2, mass), 3 var selection (D2, mass, ntrk)
PROPERTY_DECL(Props , int , isWJet_TCC_2var)
PROPERTY_DECL(Props , int , isWJet_TCC_3var)
PROPERTY_DECL(Props , int , passWMassCut_TCC_2var)
PROPERTY_DECL(Props , int , passWMassCut_TCC_3var)
PROPERTY_DECL(Props , int , passWHighMassCut_TCC_2var)
PROPERTY_DECL(Props , int , passWHighMassCut_TCC_3var)
PROPERTY_DECL(Props , int , passWLowMassCut_TCC_2var)
PROPERTY_DECL(Props , int , passWLowMassCut_TCC_3var)
PROPERTY_DECL(Props , int , passWSubstructure_TCC_2var)
PROPERTY_DECL(Props , int , passWSubstructure_TCC_3var)
PROPERTY_DECL(Props , int , passWNtrk_TCC_3var)

PROPERTY_DECL(Props , int , isZJet_TCC_2var)
PROPERTY_DECL(Props , int , isZJet_TCC_3var)
PROPERTY_DECL(Props , int , passZMassCut_TCC_2var)
PROPERTY_DECL(Props , int , passZMassCut_TCC_3var)
PROPERTY_DECL(Props , int , passZHighMassCut_TCC_2var)
PROPERTY_DECL(Props , int , passZHighMassCut_TCC_3var)
PROPERTY_DECL(Props , int , passZLowMassCut_TCC_2var)
PROPERTY_DECL(Props , int , passZLowMassCut_TCC_3var)
PROPERTY_DECL(Props , int , passZSubstructure_TCC_2var)
PROPERTY_DECL(Props , int , passZSubstructure_TCC_3var)
PROPERTY_DECL(Props , int , passZNtrk_TCC_3var)



PROPERTY_DECL( Props , float , BDTWtagScore )
PROPERTY_DECL( Props , int , nBTags )
PROPERTY_DECL( Props , int , nAddBTags )
PROPERTY_DECL( Props , int , nTrueBJets )
PROPERTY_DECL( Props , int , nTrackJets )
PROPERTY_DECL( Props , float , Tau21 )
PROPERTY_DECL( Props , float , Tau32 )
PROPERTY_DECL( Props , float , Tau21_wta )
PROPERTY_DECL( Props , float , D2 )
PROPERTY_DECL( Props , float , C2 )
PROPERTY_DECL( Props , float , Angularity )
PROPERTY_DECL( Props , float , KtDR )
PROPERTY_DECL( Props , int , xbbResult )
PROPERTY_DECL( Props , float , caloMass )
PROPERTY_DECL( Props , float , caloPt )
PROPERTY_DECL( Props , float , TAmass )
PROPERTY_DECL( Props , float , UncalibTAmass )
PROPERTY_DECL( Props , int , nGroomedTracks )
PROPERTY_DECL( Props , float , UngroomedTrackWidth500 )
PROPERTY_DECL( Props , float , UngroomedTrackWidth1000 )
PROPERTY_DECL( Props , float , UngroomedSumTrackPt500 )
PROPERTY_DECL( Props , float , UngroomedSumTrackPt1000 )
PROPERTY_DECL( Props , float , Charge )
PROPERTY_DECL( Props , float , y )
PROPERTY_DECL( Props , int , nConstituents )
PROPERTY_DECL( Props , int , nMuonSegments )
PROPERTY_DECL( Props , int , nGhostMatchedBHadrons )
PROPERTY_DECL( Props , int , nGhostMatchedCHadrons )
PROPERTY_DECL( Props , int , nGhostMatchedPromptCHadrons )
PROPERTY_DECL( Props , int , nConeMatchedBHadrons )
PROPERTY_DECL( Props , int , nConeMatchedPromptCHadrons )
PROPERTY_DECL( Props , int , nGhostMatchedTaus )
PROPERTY_DECL( Props , int , nGhostMatchedHBosons )
PROPERTY_DECL( Props , int , PartonTruthLabelIDFromUngrJet )

// e-gamma ID
//TODO: check these for photons
PROPERTY_DECL( Props, int, isVeryLoose)
PROPERTY_DECL( Props, int, isLowPtEfficiency)
PROPERTY_DECL( Props, int, isHighPt)
PROPERTY_DECL( Props, int, isTight)
PROPERTY_DECL( Props, int, isMedium)
PROPERTY_DECL( Props, int, isLoose)
PROPERTY_DECL( Props, int, isEM_Tight)
PROPERTY_DECL( Props, int, isEM_Medium)
PROPERTY_DECL( Props, int, isEM_Loose)
PROPERTY_DECL( Props, int, isAmbiguous)

// photon properties
PROPERTY_DECL( Props, uint32_t, OQ)
PROPERTY_DECL( Props, int, Author)
PROPERTY_DECL( Props, int, convType)
PROPERTY_DECL( Props, int, truthType)
PROPERTY_DECL( Props, int, truthOrigin)
// truth properties
PROPERTY_DECL( Props, float, truthpt_dressed)
PROPERTY_DECL( Props, float, truthe_dressed)
PROPERTY_DECL( Props, float, trutheta_dressed)
PROPERTY_DECL( Props, float, truthphi_dressed)
PROPERTY_DECL( Props, int  , codeTTBarDecay )
PROPERTY_DECL( Props, float, ttbarpTW )
PROPERTY_DECL( Props, float, ttbarpTL )
PROPERTY_DECL( Props, float, ttbarEtaL )
PROPERTY_DECL( Props, float, SherpapTV )
PROPERTY_DECL( Props, int  , isVZbb )
PROPERTY_DECL( Props, float, SUSYMET)
PROPERTY_DECL( Props, std::vector<float>, HTXS_V_jets25_pt)
PROPERTY_DECL( Props, std::vector<float>, HTXS_V_jets25_eta)
PROPERTY_DECL( Props, std::vector<float>, HTXS_V_jets25_phi)
PROPERTY_DECL( Props, std::vector<float>, HTXS_V_jets25_m)
PROPERTY_DECL( Props, float, GenFiltMET )

// VBF (+gamma) analysis quality assignment
PROPERTY_DECL( Props , int , isVBFLoosePhoton )
PROPERTY_DECL( Props , int , isVBFSignalPhoton )
PROPERTY_DECL( Props , int , isVBFSignalJet )
PROPERTY_DECL( Props , int , isVBFJet )
PROPERTY_DECL( Props , int , isVBFTruth )

PROPERTY_DECL( Props , int , passEvetoEffSel )
PROPERTY_DECL( Props , int , passEvetoOR )
PROPERTY_DECL( Props , int , nTracks )
PROPERTY_DECL( Props , int , nWideTracks )
PROPERTY_DECL( Props , int , nPi0PFOs ) //tau->nPi0_PFOs()
PROPERTY_DECL( Props , int , isBDTVeryLoose)
PROPERTY_DECL( Props , int , isBDTLoose )
PROPERTY_DECL( Props , int , isBDTMedium )
PROPERTY_DECL( Props , int , isBDTTight )
PROPERTY_DECL( Props , int , isRNNVeryLoose)
PROPERTY_DECL( Props , int , isRNNLoose )
PROPERTY_DECL( Props , int , isRNNMedium )
PROPERTY_DECL( Props , int , isRNNTight )
PROPERTY_DECL( Props , int , passLooseTau )
PROPERTY_DECL( Props , int , passEvetoLoose )
PROPERTY_DECL( Props , int , passEvetoMedium )
PROPERTY_DECL( Props , int , passEvetoTight )
PROPERTY_DECL( Props , int , passTauSelector )
PROPERTY_DECL( Props , int , TruthMatch )
PROPERTY_DECL( Props , int , RecoMatch )
PROPERTY_DECL( Props , int , TATTruthMatch )
PROPERTY_DECL( Props , int , LeptonTruthMatch )
PROPERTY_DECL( Props , int , passCandSel )
PROPERTY_DECL( Props , int , isHHSignalTau )
PROPERTY_DECL( Props , int , isHHRandomTau )
PROPERTY_DECL( Props , int , isHHLooseTau )
PROPERTY_DECL( Props , int , isZHSignalTau )
PROPERTY_DECL( Props , int , isZHLooseTau )
PROPERTY_DECL( Props , float , BDTScore )
PROPERTY_DECL( Props , float , BDTScoreDeprecated )
PROPERTY_DECL( Props , float , RNNScore )
PROPERTY_DECL( Props , float , RNNScoreDeprecated )
PROPERTY_DECL( Props , float , effSFeveto )
PROPERTY_DECL( Props , float , EleBDTScore )
PROPERTY_DECL( Props , float , EleORBDTscore )
PROPERTY_DECL( Props , float , EleORLH)
PROPERTY_DECL( Props , float , TrackEta )

PROPERTY_DECL( Props , int , isTrackJet )
PROPERTY_DECL( Props , int , TrkJetnumConstituents )
//PROPERTY_DECL( Props , int , passTaggingReq )
PROPERTY_DECL( Props , int , VRJetOverlap )


PROPERTY_DECL( Props , int , TTLH_isvbf )
PROPERTY_DECL( Props , int , TTLH_isboost )
PROPERTY_DECL( Props , int , TTLH_presel )
PROPERTY_DECL( Props , int , TTLH_dilepcr )
PROPERTY_DECL( Props , int , TTLH_os )
PROPERTY_DECL( Props , int , TTLH_hasbtag )
PROPERTY_DECL( Props , int , TTLH_iselhad )
PROPERTY_DECL( Props , int , isMC )
PROPERTY_DECL( Props , int , NVtx3Trks )
PROPERTY_DECL( Props , int , NVtx2Trks )
PROPERTY_DECL( Props , int , NTruthWZJets20 )
PROPERTY_DECL( Props , int , NTruthWZJets30 )
PROPERTY_DECL( Props , int , HTXS_prodMode )
PROPERTY_DECL( Props , int , HTXS_Stage0_Category )
PROPERTY_DECL( Props , int , HTXS_Stage1_Category_pTjet25 )
PROPERTY_DECL( Props , int , HTXS_Stage1_Category_pTjet30 )
PROPERTY_DECL( Props , int , HTXS_Njets_pTjet25 )
PROPERTY_DECL( Props , int , HTXS_Njets_pTjet30 )
PROPERTY_DECL( Props , int , hasPV )
PROPERTY_DECL( Props , int , passGRL )
PROPERTY_DECL( Props , int , isCleanEvent )
PROPERTY_DECL( Props , char , DFCommonJets_isBadBatman )
PROPERTY_DECL( Props , int , DFCommonJets_eventClean_LooseBad )
PROPERTY_DECL( Props , int , TTLH_njets )
PROPERTY_DECL( Props , int , TriggerStream )
PROPERTY_DECL( Props , int , passTrigger )
// trigger flags
PROPERTY_DECL( Props , int , passHLT_xe80_tc_lcw_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe90_mht_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe90_tc_lcw_wEFMu_L1XE50  )
PROPERTY_DECL( Props , int , passHLT_xe90_mht_wEFMu_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe100_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe100_L1XE60 )
PROPERTY_DECL( Props , int , passHLT_xe100_tc_em_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe120_pueta )
PROPERTY_DECL( Props , int , passHLT_xe120_pueta_wEFMu )
PROPERTY_DECL( Props , int , passHLT_xe90_pufit_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe90_pufit_L1XE55 )
PROPERTY_DECL( Props , int , passHLT_xe100_pufit_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe100_pufit_L1XE55 )
PROPERTY_DECL( Props , int , passHLT_xe110_pufit_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe110_pufit_L1XE55 )
PROPERTY_DECL( Props , int , passHLT_xe110_pufit_L1XE60 )
PROPERTY_DECL( Props , int , passHLT_xe110_pufit_xe65_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe110_pufit_xe70_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe120_pufit_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe120_pufit_L1XE55 )
PROPERTY_DECL( Props , int , passHLT_xe120_pufit_L1XE60 )
PROPERTY_DECL( Props , int , passHLT_xe120_pufit )
PROPERTY_DECL( Props , int , passHLT_xe120_pufit_wEFMu )
PROPERTY_DECL( Props , int , passHLT_xe120_mht )
PROPERTY_DECL( Props , int , passHLT_xe120_mht_wEFMu )
PROPERTY_DECL( Props , int , passHLT_xe120_tc_em )
PROPERTY_DECL( Props , int , passHLT_xe120_tc_lcw )
PROPERTY_DECL( Props , int , passHLT_xe120_tc_lcw_wEFMu )
PROPERTY_DECL( Props , int , passHLT_xe90_tc_lcw_L1XE50  )
PROPERTY_DECL( Props , int , passHLT_xe100_tc_lcw_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe100_tc_lcw_L1XE60 )
PROPERTY_DECL( Props , int , passHLT_xe110_tc_em_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe110_tc_em_wEFMu_L1XE50 )
PROPERTY_DECL( Props , int , passHLT_xe110_tc_lcw_L1XE60 )
PROPERTY_DECL( Props , int , passHLT_xe80_mht_L1XE50     )
PROPERTY_DECL( Props , int , passHLT_xe100_mht_L1XE50    )
PROPERTY_DECL( Props , int , passHLT_xe100_mht_L1XE60    )
PROPERTY_DECL( Props , int , passHLT_xe110_mht_L1XE50    )
PROPERTY_DECL( Props , int , passHLT_xe110_mht_L1XE50_AND_xe70_L1XE50    )
PROPERTY_DECL( Props , int , passHLT_xe110_mht_L1XE50_AND_xe70_L1XE55    )
PROPERTY_DECL( Props , int , passHLT_xe130_mht_L1XE50    )
PROPERTY_DECL( Props , int , passHLT_xe80_L1XE50         )
PROPERTY_DECL( Props , int , passHLT_xe90_L1XE50         )
PROPERTY_DECL( Props , int , passHLT_xe110_L1XE50        )
PROPERTY_DECL( Props , int , passHLT_xe110_L1XE60        )
PROPERTY_DECL( Props , int , passHLT_xe80_tc_em_L1XE50   )
PROPERTY_DECL( Props , int , passHLT_xe90_tc_em_L1XE50   )
PROPERTY_DECL( Props , int , passL1_XE60 )
PROPERTY_DECL( Props , int , passL1_XE70 )
PROPERTY_DECL( Props , int , passHLT_xe70 )
PROPERTY_DECL( Props , int , passHLT_xe80 )
PROPERTY_DECL( Props , int , passHLT_xe100 )
PROPERTY_DECL( Props , int , passL1_J40_DPHI_J20XE50 )
PROPERTY_DECL( Props , int , passL1_J40_DPHI_J20s2XE50 )
PROPERTY_DECL( Props , int , passHLT_j80_xe80_dphi1_L1J40_DPHI_J20XE50 )
PROPERTY_DECL( Props , int , passHLT_j80_xe80_dphi1_L1J40_DPHI_J20s2XE50 )
PROPERTY_DECL( Props , int , passHLT_j100_xe80_L1J40_DPHI_J20XE50 )
PROPERTY_DECL( Props , int , passHLT_j100_xe80_L1J40_DPHI_J20s2XE50 )
PROPERTY_DECL( Props , int , passL1_EM13VH )
PROPERTY_DECL( Props , int , passL1_EM15VH )
PROPERTY_DECL( Props , int , passL1_EM18VH )
PROPERTY_DECL( Props , int , passL1_EM20VH )
PROPERTY_DECL( Props , int , passL1_EM22VHI )
PROPERTY_DECL( Props , int , passL1_2EM15VH )
PROPERTY_DECL( Props , int , passHLT_e15_lhtight_ivarloose_3j20_L1EM13VH_3J20 )
PROPERTY_DECL( Props , int , passHLT_mu14_ivarloose_3j20_L1MU10_3J20 )
PROPERTY_DECL( Props , int , passHLT_e17_lhloose_L1EM15 )
PROPERTY_DECL( Props , int , passHLT_e22_lhvloose_nod0_e12_lhvloose_nod0_e10_lhvloose_nod0 )
PROPERTY_DECL( Props , int , passHLT_e24_lhvloose_L1EM18VH )
PROPERTY_DECL( Props , int , passHLT_e24_lhvloose_L1EM20VH )
PROPERTY_DECL( Props , int , passHLT_e24_lhvloose_nod0_L1EM20VH )
PROPERTY_DECL( Props , int , passHLT_e24_lhvloose_nod0_2e12_lhvloose_nod0_L1EM20VH_3EM10VH )
PROPERTY_DECL( Props , int , passHLT_e24_medium_iloose_L1EM18VH )
PROPERTY_DECL( Props , int , passHLT_e24_medium_iloose_L1EM20VH )
PROPERTY_DECL( Props , int , passHLT_e24_lhmedium_iloose_L1EM18VH )
PROPERTY_DECL( Props , int , passHLT_e24_lhmedium_iloose_L1EM20VH )
PROPERTY_DECL( Props , int , passHLT_e24_lhmedium_L1EM18VH )
PROPERTY_DECL( Props , int , passHLT_e24_lhmedium_L1EM20VH )
PROPERTY_DECL( Props , int , passHLT_e24_tight_iloose )
PROPERTY_DECL( Props , int , passHLT_e24_lhtight_iloose )
PROPERTY_DECL( Props , int , passHLT_e26_lhvloose_nod0_L1EM20VH)
PROPERTY_DECL( Props , int , passHLT_e26_lhmedium_nod0_L1EM20VH)
PROPERTY_DECL( Props , int , passHLT_e26_lhmedium_nod0_ivarloose)
PROPERTY_DECL( Props , int , passHLT_e26_tight_iloose )
PROPERTY_DECL( Props , int , passHLT_e26_tight1_iloose )
PROPERTY_DECL( Props , int , passHLT_e26_lhtight_iloose )
PROPERTY_DECL( Props , int , passHLT_e26_lhtight_ivarloose )
PROPERTY_DECL( Props , int , passHLT_e26_lhtight_smooth_ivarloose )
PROPERTY_DECL( Props , int , passHLT_e60_medium )
PROPERTY_DECL( Props , int , passHLT_e60_medium1 )
PROPERTY_DECL( Props , int , passHLT_e60_lhmedium )
PROPERTY_DECL( Props , int , passHLT_e60_lhmedium_nod0 )
PROPERTY_DECL( Props , int , passHLT_e60_lhmedium_nod0_L1EM24VHI )
PROPERTY_DECL( Props , int , passHLT_e80_lhmedium_nod0 )
PROPERTY_DECL( Props , int , passHLT_e120_lhloose )
PROPERTY_DECL( Props , int , passHLT_e120_lhloose_nod0 )
PROPERTY_DECL( Props , int , passHLT_e140_lhloose )
PROPERTY_DECL( Props , int , passHLT_e140_lhloose_nod0 )
PROPERTY_DECL( Props , int , passHLT_e140_lhloose_nod0_L1EM24VHI )
PROPERTY_DECL( Props , int , passHLT_e300_etcut )
PROPERTY_DECL( Props , int , passHLT_e300_etcut_L1EM24VHI )
PROPERTY_DECL( Props , int , passHLT_2e17_loose )
PROPERTY_DECL( Props , int , passHLT_2e17_loose1 )
PROPERTY_DECL( Props , int , passHLT_2e17_lhloose )
PROPERTY_DECL( Props , int , passHLT_2e17_lhvloose_nod0_L12EM15VHI )
PROPERTY_DECL( Props , int , passHLT_2e24_lhvloose_nod0 )
PROPERTY_DECL( Props , int , passHLT_e17_lhloose_mu14 )
PROPERTY_DECL( Props , int , passHLT_e17_lhloose_nod0_mu14 )
PROPERTY_DECL( Props , int , passHLT_e26_lhmedium_nod0_mu8noL1 )
PROPERTY_DECL( Props , int , passHLT_e26_lhmedium_nod0_L1EM22VHI_mu8noL1 )
PROPERTY_DECL( Props , int , passHLT_e7_lhmedium_mu24 )
PROPERTY_DECL( Props , int , passHLT_e7_lhmedium_nod0_mu24 )
PROPERTY_DECL( Props , int , passL1_MU20 )
PROPERTY_DECL( Props , int , passL1_2MU10 )
PROPERTY_DECL( Props , int , passHLT_mu14 )
PROPERTY_DECL( Props , int , passHLT_mu20_iloose_L1MU15 )
PROPERTY_DECL( Props , int , passHLT_mu20_2mu4noL1 )
PROPERTY_DECL( Props , int , passHLT_mu24_iloose_L1MU15 )
PROPERTY_DECL( Props , int , passHLT_mu24_imedium )
PROPERTY_DECL( Props , int , passHLT_mu26_imedium )
PROPERTY_DECL( Props , int , passHLT_mu40 )
PROPERTY_DECL( Props , int , passHLT_mu50 )
PROPERTY_DECL( Props , int , passHLT_mu50_0eta105_msonly )
PROPERTY_DECL( Props , int , passHLT_mu60 )
PROPERTY_DECL( Props , int , passHLT_mu60_0eta105_msonly )
PROPERTY_DECL( Props , int , passHLT_mu80 )
PROPERTY_DECL( Props , int , passHLT_2mu10 )
PROPERTY_DECL( Props , int , passHLT_2mu14 )
PROPERTY_DECL( Props , int , passHLT_mu18_mu8noL1 )
PROPERTY_DECL( Props , int , passHLT_mu24_mu8noL1 )
PROPERTY_DECL( Props , int , passHLT_mu24_mu8noL1_calotag_0eta010 )
PROPERTY_DECL( Props , int , passHLT_e28_lhtight_nod0_ivarloose )
PROPERTY_DECL( Props , int , passHLT_e28_lhtight_nod0_ivarloose_L1EM24VHIM )
PROPERTY_DECL( Props , int , passHLT_e26_lhtight_nod0_ivarloose )
PROPERTY_DECL( Props , int , passHLT_e26_lhtight_nod0_ivarloose_L1EM22VHIM )
PROPERTY_DECL( Props , int , passHLT_e26_lhtight_nod0 )
PROPERTY_DECL( Props , int , passHLT_e24_lhtight_ivarloose )
PROPERTY_DECL( Props , int , passHLT_e24_lhtight_nod0_ivarloose )
PROPERTY_DECL( Props , int , passHLT_e24_lhmedium_ivarloose )
PROPERTY_DECL( Props , int , passHLT_e24_lhmedium_nod0_ivarloose )
PROPERTY_DECL( Props , int , passHLT_e24_lhmedium_nod0_L1EM20VH )
PROPERTY_DECL( Props , int , passHLT_2e17_lhloose_nod0 )
PROPERTY_DECL( Props , int , passHLT_2e17_lhvloose_nod0 )
PROPERTY_DECL( Props , int , passHLT_2e15_lhloose_L12EM13VH )
PROPERTY_DECL( Props , int , passHLT_2e15_lhloose_nod0_L12EM13VH )
PROPERTY_DECL( Props , int , passHLT_2e12_lhloose_L12EM10VH )
PROPERTY_DECL( Props , int , passHLT_2e12_lhloose_nod0_L12EM10VH )
PROPERTY_DECL( Props , int , passHLT_mu28_ivarmedium )
PROPERTY_DECL( Props , int , passHLT_mu26_ivarmedium )
PROPERTY_DECL( Props , int , passHLT_mu24_ivarmedium )
PROPERTY_DECL( Props , int , passHLT_mu24_ivarloose )
PROPERTY_DECL( Props , int , passHLT_mu24_ivarloose_L1MU15 )
PROPERTY_DECL( Props , int , passHLT_mu24_iloose )
PROPERTY_DECL( Props , int , passHLT_mu22_mu8noL1 )
PROPERTY_DECL( Props , int , passHLT_mu22_mu8noL1_calotag_0eta010 )
PROPERTY_DECL( Props , int , passHLT_mu20_mu8noL1 )
PROPERTY_DECL( Props , int , passHLT_mu4_j15_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu4_j25_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu4_j35_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu4_j55_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu6_j85_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu6_j110_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu6_j150_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu6_j175_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu6_j260_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu6_j320_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu6_j400_dr05 )
PROPERTY_DECL( Props , int , passHLT_mu4_j15_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu4_j25_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu4_j35_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu4_j55_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu6_j85_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu6_j110_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu6_j150_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu6_j175_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu6_j260_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu6_j320_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_mu6_j400_bperf_split_dr05_dz02 )
PROPERTY_DECL( Props , int , passHLT_g10_loose )
PROPERTY_DECL( Props , int , passHLT_g15_loose_L1EM7 )
PROPERTY_DECL( Props , int , passHLT_g20_loose_L1EM12 )
PROPERTY_DECL( Props , int , passHLT_g25_loose_L1EM15 )
PROPERTY_DECL( Props , int , passHLT_g35_loose_L1EM15 )
PROPERTY_DECL( Props , int , passHLT_g40_loose_L1EM15 )
PROPERTY_DECL( Props , int , passHLT_g45_loose_L1EM15 )
PROPERTY_DECL( Props , int , passHLT_g50_loose_L1EM15 )
PROPERTY_DECL( Props , int , passHLT_g60_loose )
PROPERTY_DECL( Props , int , passHLT_g70_loose )
PROPERTY_DECL( Props , int , passHLT_g80_loose )
PROPERTY_DECL( Props , int , passHLT_g90_loose )
PROPERTY_DECL( Props , int , passHLT_g100_loose )
PROPERTY_DECL( Props , int , passHLT_g120_loose )
PROPERTY_DECL( Props , int , passHLT_g140_loose )
PROPERTY_DECL( Props , int , passHLT_g140_tight )
PROPERTY_DECL( Props , int , passHLT_g200_loose )
PROPERTY_DECL( Props , int , passHLT_g300_etcut )
PROPERTY_DECL( Props , int , passHLT_g300_etcut_L1EM24VHI )
PROPERTY_DECL( Props , int , passL1_J100 )
PROPERTY_DECL( Props , int , passL1_MJJ_400 )
PROPERTY_DECL( Props , int , passL1_MJJ_700 )
PROPERTY_DECL( Props , int , passL1_MJJ_800 )
PROPERTY_DECL( Props , int , passL1_MJJ_900 )
PROPERTY_DECL( Props , int , passL1_J30_2J20_4J20_0ETA49_MJJ_400 )
PROPERTY_DECL( Props , int , passL1_J30_2J20_4J20_0ETA49_MJJ_700 )
PROPERTY_DECL( Props , int , passL1_J30_2J20_4J20_0ETA49_MJJ_800 )
PROPERTY_DECL( Props , int , passL1_J30_2J20_4J20_0ETA49_MJJ_900 )
PROPERTY_DECL( Props , int , passL1_3J20_4J20_0ETA49_MJJ_400 )
PROPERTY_DECL( Props , int , passL1_3J20_4J20_0ETA49_MJJ_700 )
PROPERTY_DECL( Props , int , passL1_3J20_4J20_0ETA49_MJJ_800 )
PROPERTY_DECL( Props , int , passL1_3J20_4J20_0ETA49_MJJ_900 )
PROPERTY_DECL( Props , int , passL1_4J20_0ETA49 )
PROPERTY_DECL( Props , int , passHLT_g15_loose_2j40_0eta490_3j25_0eta490 )
PROPERTY_DECL( Props , int , passHLT_g20_loose_2j40_0eta490_3j25_0eta490 )
PROPERTY_DECL( Props , int , passHLT_g20_loose_2j40_0eta490_3j25_0eta490_L1MJJ_700 )
PROPERTY_DECL( Props , int , passHLT_g20_loose_2j40_0eta490_3j25_0eta490_L1MJJ_900 )
PROPERTY_DECL( Props , int , passHLT_g20_loose_L1EM18VH_2j40_0eta490_3j25_0eta490 )
PROPERTY_DECL( Props , int , passHLT_g20_loose_L1EM18VH_2j40_0eta490_3j25_0eta490_invm700 )
PROPERTY_DECL( Props , int , passHLT_g25_loose_L1EM20VH_2j40_0eta490_3j25_0eta490_invm700 )
PROPERTY_DECL( Props , int , passHLT_g25_loose_2j40_0eta490_3j25_0eta490_invm700 )
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_4j35_0eta490_invm700)
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_4j35_0eta490_invm1000)
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_j35_0eta490_bmv2c2077_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_2j35_0eta490_bmv2c2077_2j35_0eta490)
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_j35_0eta490_bmv2c2077_split_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_2j35_0eta490_bmv2c2077_split_2j35_0eta490)
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_j35_0eta490_bmv2c1077_split_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_2j35_0eta490_bmv2c1077_split_2j35_0eta490)
PROPERTY_DECL( Props , int , passHLT_g20_tight_icaloloose_j15_gsc35_bmv2c1077_split_3j35_0eta490_invm500)
PROPERTY_DECL( Props , int , passHLT_g20_tight_icaloloose_j35_bmv2c1077_split_3j35_0eta490_invm500)
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_j35_0eta490_boffperf_split_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , passHLT_g25_medium_L1EM22VHI_2j35_0eta490_boffperf_split_2j35_0eta490)
PROPERTY_DECL( Props , int , passHLT_g25_loose_L1EM20VH_4j35_0eta490)
PROPERTY_DECL( Props , int , passHLT_2j55_bperf_L1J30_2J20_4J20_0ETA49_MJJ_400 )
PROPERTY_DECL( Props , int , passHLT_2j55_bperf_L1J30_2J20_4J20_0ETA49_MJJ_700 )
PROPERTY_DECL( Props , int , passHLT_2j55_bperf_L1J30_2J20_4J20_0ETA49_MJJ_800 )
PROPERTY_DECL( Props , int , passHLT_2j55_bperf_L1J30_2J20_4J20_0ETA49_MJJ_900 )
PROPERTY_DECL( Props , int , passHLT_2j55_bperf_L13J20_4J20_0ETA49_MJJ_400 )
PROPERTY_DECL( Props , int , passHLT_2j55_bperf_L13J20_4J20_0ETA49_MJJ_700 )
PROPERTY_DECL( Props , int , passHLT_2j55_bperf_L13J20_4J20_0ETA49_MJJ_800 )
PROPERTY_DECL( Props , int , passHLT_2j55_bperf_L13J20_4J20_0ETA49_MJJ_900 )
PROPERTY_DECL( Props , int , passHLT_2j55_bperf_L14J20_0ETA49 )
PROPERTY_DECL( Props , int , passHLT_2j55_bloose_L1J30_2J20_4J20_0ETA49_MJJ_400 )
PROPERTY_DECL( Props , int , passHLT_2j55_bloose_L1J30_2J20_4J20_0ETA49_MJJ_700 )
PROPERTY_DECL( Props , int , passHLT_2j55_bloose_L1J30_2J20_4J20_0ETA49_MJJ_800 )
PROPERTY_DECL( Props , int , passHLT_2j55_bloose_L1J30_2J20_4J20_0ETA49_MJJ_900 )
PROPERTY_DECL( Props , int , passHLT_2j55_bloose_L13J20_4J20_0ETA49_MJJ_400 )
PROPERTY_DECL( Props , int , passHLT_2j55_bloose_L13J20_4J20_0ETA49_MJJ_700 )
PROPERTY_DECL( Props , int , passHLT_2j55_bloose_L13J20_4J20_0ETA49_MJJ_800 )
PROPERTY_DECL( Props , int , passHLT_2j55_bloose_L13J20_4J20_0ETA49_MJJ_900 )
PROPERTY_DECL( Props , int , passHLT_2j55_bloose_L14J20_0ETA49 )
PROPERTY_DECL( Props , int , passHLT_2j55_bmedium_L13J20_4J20_0ETA49_MJJ_400 )
PROPERTY_DECL( Props , int , passHLT_2j55_bmedium_L13J20_4J20_0ETA49_MJJ_700 )
PROPERTY_DECL( Props , int , passHLT_2j55_bmedium_L13J20_4J20_0ETA49_MJJ_800 )
PROPERTY_DECL( Props , int , passHLT_2j55_bmedium_L13J20_4J20_0ETA49_MJJ_900 )
PROPERTY_DECL( Props , int , passHLT_2j55_bmedium_L1J30_2J20_4J20_0ETA49_MJJ_400 )
PROPERTY_DECL( Props , int , passHLT_2j55_bmedium_L1J30_2J20_4J20_0ETA49_MJJ_700 )
PROPERTY_DECL( Props , int , passHLT_2j55_bmedium_L1J30_2J20_4J20_0ETA49_MJJ_800 )
PROPERTY_DECL( Props , int , passHLT_2j55_bmedium_L1J30_2J20_4J20_0ETA49_MJJ_900 )
PROPERTY_DECL( Props , int , passHLT_2j55_bmedium_L14J20_0ETA49 )
PROPERTY_DECL( Props , int , passL1_EM20VHI )
PROPERTY_DECL( Props , int , passL1_MU15 )
PROPERTY_DECL( Props , int , passL1_XE50 )
PROPERTY_DECL( Props , int , passL1_XE35 )
PROPERTY_DECL( Props , int , passHLT_xe35 )
PROPERTY_DECL( Props , int , passHLT_xe50 )
PROPERTY_DECL( Props , int , passHLT_xe60 )
PROPERTY_DECL( Props , int , passL1_XE40 )
//tau triggers
PROPERTY_DECL( Props , int ,passHLT_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_tau25_medium1_tracktwo_L1TAU12)
PROPERTY_DECL( Props , int ,passHLT_tau25_medium1_tracktwo_L1TAU12IL)
PROPERTY_DECL( Props , int ,passHLT_tau25_medium1_tracktwo_L1TAU12IT)
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo )
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_L1TAU20 )
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_L1TAU20IL )
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_L1TAU20IT )
PROPERTY_DECL( Props , int ,passHLT_tau50_medium1_tracktwo_L1TAU12 )
PROPERTY_DECL( Props , int ,passHLT_tau80_medium1_tracktwo )
PROPERTY_DECL( Props , int ,passHLT_tau80_medium1_tracktwo_L1TAU60 )
PROPERTY_DECL( Props , int ,passHLT_tau125_medium1_tracktwo )
PROPERTY_DECL( Props , int ,passHLT_tau160_medium1_tracktwo )
PROPERTY_DECL( Props , int ,passHLT_tau160_medium1_tracktwo_L1TAU100 )
PROPERTY_DECL( Props , int ,passHLT_tau160_medium1_tracktwoEF_L1TAU100 )
PROPERTY_DECL( Props , int ,passHLT_tau160_mediumRNN_tracktwoMVA_L1TAU100 )
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_L1TAU20IM_2TAU12IM )
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_L1TAU20_tau25_medium1_tracktwo_L1TAU12 )
PROPERTY_DECL( Props , int ,passHLT_tau40_medium1_tracktwo_tau35_medium1_tracktwo )
PROPERTY_DECL( Props , int ,passHLT_tau40_mediumRNN_tracktwoMVA_tau35_mediumRNN_tracktwoMVA )
PROPERTY_DECL( Props , int ,passHLT_tau60_medium1_tracktwo_tau25_medium1_tracktwo_xe50 )

PROPERTY_DECL( Props , int ,passHLT_tau80_medium1_TAU60_tau50_medium1_L1TAU12)
PROPERTY_DECL( Props , int ,passHLT_tau80_medium1_tracktwo_L1TAU60_tau50_medium1_tracktwo_L1TAU12 )
PROPERTY_DECL( Props , int ,passHLT_tau80_medium1_tracktwo_L1TAU60_tau35_medium1_tracktwo_L1TAU12IM_L1TAU60_DR_TAU20ITAU12I )
PROPERTY_DECL( Props , int ,passHLT_tau80_medium1_tracktwo_L1TAU60_tau60_medium1_tracktwo_L1TAU40 )
PROPERTY_DECL( Props , int ,passHLT_tau125_medium1_tracktwo_tau50_medium1_tracktwo_L1TAU12 )
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_03dR30_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwoEF_tau25_medium1_tracktwoEF_03dR30_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_tau35_mediumRNN_tracktwoMVA_tau25_mediumRNN_tracktwoMVA_03dR30_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwoEF_tau25_medium1_tracktwoEF_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_tau35_mediumRNN_tracktwoMVA_tau25_mediumRNN_tracktwoMVA_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_L1DR_TAU20ITAU12I )
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_L1TAU20IM_2TAU12IM_4J12)
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwoEF_tau25_medium1_tracktwoEF_L1TAU20IM_2TAU12IM_4J12_0ETA23)
PROPERTY_DECL( Props , int ,passHLT_tau35_mediumRNN_tracktwoMVA_tau25_mediumRNN_tracktwoMVA_L1TAU20IM_2TAU12IM_4J12_0ETA23)
PROPERTY_DECL( Props , int ,passHLT_e17_medium_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_medium_iloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_iloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_medium_tau80_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_tau80_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_tau80_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_iloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_iloose_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e24_lhmedium_nod0_ivarloose_tau35_medium1_tracktwo)
//
PROPERTY_DECL( Props , int ,passHLT_mu14_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_mu14_tau35_medium1_tracktwo_L1TAU20)
PROPERTY_DECL( Props , int ,passHLT_mu14_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_mu14_iloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_mu14_iloose_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_L1TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_tau35_loose1_tracktwo_tau25_loose1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_tau35_loose1_tracktwo_tau25_loose1_tracktwo_L1TAU20IM_2TAU12IM)
PROPERTY_DECL( Props , int ,passHLT_tau40_medium1_tracktwoEF_tau35_medium1_tracktwoEF)
PROPERTY_DECL( Props , int ,passHLT_tau80_medium1_tracktwoEF_L1TAU60_tau35_medium1_tracktwoEF_L1TAU12IM_L1TAU60_DR_TAU20ITAU12I)
PROPERTY_DECL( Props , int ,passHLT_tau80_medium1_tracktwoEF_L1TAU60_tau60_medium1_tracktwoEF_L1TAU40)
PROPERTY_DECL( Props , int ,passHLT_tau80_mediumRNN_tracktwoMVA_L1TAU60_tau35_mediumRNN_tracktwoMVA_L1TAU12IM_L1TAU60_DR_TAU20ITAU12I)
PROPERTY_DECL( Props , int ,passHLT_tau80_mediumRNN_tracktwoMVA_L1TAU60_tau60_mediumRNN_tracktwoMVA_L1TAU40)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwo_L1DR_EM15TAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwo_L1EM15VHI_2TAU12IM_4J12)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau25_medium1_tracktwo_L1DR_MU10TAU12I_TAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau35_medium1_tracktwo_L1MU10_TAU20IM_J25_2J20)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau25_medium1_tracktwo_L1MU10_TAU12IM_3J12)

// 2018 LepTau triggers
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwoEF)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau25_mediumRNN_tracktwoMVA)

// backup
PROPERTY_DECL( Props , int ,passHLT_e24_lhmedium_nod0_ivarloose_tau35_medium1_tracktwoEF)
PROPERTY_DECL( Props , int ,passHLT_e24_lhmedium_nod0_ivarloose_tau35_mediumRNN_tracktwoMVA)

PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwoEF_L1DR_EM15TAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau25_mediumRNN_tracktwoMVA_L1DR_EM15TAU12I_J25)

PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwoEF_L1EM15VHI_2TAU12IM_4J12)
PROPERTY_DECL( Props , int ,passHLT_e17_lhmedium_nod0_ivarloose_tau25_mediumRNN_tracktwoMVA_L1EM15VHI_2TAU12IM_4J12)

PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau35_medium1_tracktwoEF)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau35_mediumRNN_tracktwoMVA)

PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau25_medium1_tracktwoEF)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau25_mediumRNN_tracktwoMVA)

// backup
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau35_medium1_tracktwoEF_L1MU10_TAU20IM_J25_2J20)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau35_mediumRNN_tracktwoMVA_L1MU10_TAU20IM_J25_2J20)

PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau25_medium1_tracktwoEF_L1DR_MU10TAU12I_TAU12I_J25)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau25_mediumRNN_tracktwoMVA_L1DR_MU10TAU12I_TAU12I_J25)

PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau25_medium1_tracktwoEF_L1MU10_TAU12IM_3J12)
PROPERTY_DECL( Props , int ,passHLT_mu14_ivarloose_tau25_mediumRNN_tracktwoMVA_L1MU10_TAU12IM_3J12)



//
PROPERTY_DECL( Props , int ,passHLT_e20_lhtight_nod0_ivarloose_3j20_L1EM18VHI_3J20)
PROPERTY_DECL( Props , int ,passHLT_mu20_ivarmedium_L1MU10_2J20)
PROPERTY_DECL( Props , int ,passHLT_mu20_ivarmedium_L1MU10_2J15_J20)

// jet trigger
PROPERTY_DECL( Props , int , passHLT_j15 )
PROPERTY_DECL( Props , int , passHLT_j25 )
PROPERTY_DECL( Props , int , passHLT_j35 )
PROPERTY_DECL( Props , int , passHLT_j45 )
PROPERTY_DECL( Props , int , passHLT_j55 )
PROPERTY_DECL( Props , int , passHLT_j60 )
PROPERTY_DECL( Props , int , passHLT_j85 )
PROPERTY_DECL( Props , int , passHLT_j100 )
PROPERTY_DECL( Props , int , passHLT_j110 )
PROPERTY_DECL( Props , int , passHLT_j150 )
PROPERTY_DECL( Props , int , passHLT_j175 )
PROPERTY_DECL( Props , int , passHLT_j200 )
PROPERTY_DECL( Props , int , passHLT_j260 )
PROPERTY_DECL( Props , int , passHLT_j300 )
PROPERTY_DECL( Props , int , passHLT_j320 )
PROPERTY_DECL( Props , int , passHLT_j360 )
PROPERTY_DECL( Props , int , passHLT_j380 )
PROPERTY_DECL( Props , int , passHLT_j400 )
PROPERTY_DECL( Props , int , passHLT_j420 )
PROPERTY_DECL( Props , int , passHLT_j440 )
PROPERTY_DECL( Props , int , passHLT_j450 )
PROPERTY_DECL( Props , int , passHLT_j460 )
PROPERTY_DECL( Props , int , passHLT_j45_bperf )
PROPERTY_DECL( Props , int , passHLT_noalg_L1J400 )
PROPERTY_DECL( Props , int , passHLT_j260_a10_lcw_L1J75)
PROPERTY_DECL( Props , int , passHLT_j260_a10_lcw_nojcalib_L1J75)
PROPERTY_DECL( Props , int , passHLT_j260_a10_nojcalib_L1J75)
PROPERTY_DECL( Props , int , passHLT_j260_a10_sub_L1J75)
PROPERTY_DECL( Props , int , passHLT_j260_a10_lcw_sub_L1J75)
PROPERTY_DECL( Props , int , passHLT_j300_a10_sub_L1J75)
PROPERTY_DECL( Props , int , passHLT_j300_a10_lcw_L1J75)
PROPERTY_DECL( Props , int , passHLT_j360_a10_lcw_L1J100)
PROPERTY_DECL( Props , int , passHLT_j380_a10_lcw_L1J100)
PROPERTY_DECL( Props , int , passHLT_j400_a10_lcw_L1J100)
PROPERTY_DECL( Props , int , passHLT_j420_a10_lcw_L1J100)
PROPERTY_DECL( Props , int , passHLT_j440_a10_lcw_L1J100)
PROPERTY_DECL( Props , int , passHLT_j460_a10_sub_L1J100)
PROPERTY_DECL( Props , int , passHLT_j460_a10_lcw_L1J100)
PROPERTY_DECL( Props , int , passHLT_j460_a10_nojcalib_L1J100)
PROPERTY_DECL( Props , int , passHLT_j460_a10_lcw_nojcalib_L1J100)
PROPERTY_DECL( Props , int , passHLT_j460_a10_lcw_sub_L1J100)
PROPERTY_DECL( Props , int , passHLT_j460_a10_lcw_subjes_L1J100)
PROPERTY_DECL( Props , int , passHLT_j480_a10_lcw_subjes_L1J100)
PROPERTY_DECL( Props , int , passHLT_j300_a10_lcw_sub_L1SC85)
PROPERTY_DECL( Props , int , passHLT_j300_a10_lcw_L1SC85)
PROPERTY_DECL( Props , int , passHLT_j260_a10r_L1J75)
PROPERTY_DECL( Props , int , passHLT_j300_a10r_L1J75)
PROPERTY_DECL( Props , int , passHLT_j360_a10r_L1J100)
PROPERTY_DECL( Props , int , passHLT_j380_a10r_L1J100)
PROPERTY_DECL( Props , int , passHLT_j400_a10r_L1J100)
PROPERTY_DECL( Props , int , passHLT_j420_a10r_L1J100)
PROPERTY_DECL( Props , int , passHLT_j440_a10r_L1J100)
PROPERTY_DECL( Props , int , passHLT_j460_a10r_L1J100)
PROPERTY_DECL( Props , int , passHLT_j480_a10r_L1J100)

// trigger objects
PROPERTY_DECL( Props , std::vector<float> , L1_METet )
PROPERTY_DECL( Props , std::vector<float> , L1_METphi )
PROPERTY_DECL( Props , std::vector<float> , HLT_METet )
PROPERTY_DECL( Props , std::vector<float> , HLT_METphi )
PROPERTY_DECL( Props , std::vector<float> , L1_JetPt )
PROPERTY_DECL( Props , std::vector<float> , L1_JetPhi )
PROPERTY_DECL( Props , std::vector<float> , L1_JetEta )
PROPERTY_DECL( Props , std::vector<float> , HLT_JetPt )
PROPERTY_DECL( Props , std::vector<float> , HLT_JetPhi )
PROPERTY_DECL( Props , std::vector<float> , HLT_JetEta )
PROPERTY_DECL( Props , std::vector<float> , L1_EMEt )
PROPERTY_DECL( Props , std::vector<float> , L1_EMPhi )
PROPERTY_DECL( Props , std::vector<float> , L1_EMEta )
PROPERTY_DECL( Props , std::vector<float> , L2_PhotonPt )
PROPERTY_DECL( Props , std::vector<float> , L2_PhotonPhi )
PROPERTY_DECL( Props , std::vector<float> , L2_PhotonEta )
PROPERTY_DECL( Props , std::vector<float> , HLT_PhotonPt )
PROPERTY_DECL( Props , std::vector<float> , HLT_PhotonPhi )
PROPERTY_DECL( Props , std::vector<float> , HLT_PhotonEta )
PROPERTY_DECL( Props , std::vector<float> , L1_MuonPt )
PROPERTY_DECL( Props , std::vector<float> , L1_MuonEta )
PROPERTY_DECL( Props , std::vector<float> , L1_MuonPhi )
PROPERTY_DECL( Props , std::vector<float> , HLT_MuonPt )
PROPERTY_DECL( Props , std::vector<float> , HLT_MuonEta )
PROPERTY_DECL( Props , std::vector<float> , HLT_MuonPhi )
PROPERTY_DECL( Props , std::vector<float> , HLT_ElectronPt )
PROPERTY_DECL( Props , std::vector<float> , HLT_ElectronEta )
PROPERTY_DECL( Props , std::vector<float> , HLT_ElectronPhi )
PROPERTY_DECL( Props , std::vector<float> , L1_ElectronPt )
PROPERTY_DECL( Props , std::vector<float> , L1_ElectronEta )
PROPERTY_DECL( Props , std::vector<float> , L1_ElectronPhi )

PROPERTY_DECL( Props , float , MCEventWeight )
PROPERTY_DECL( Props , std::vector<float> , MCEventWeightSys )
PROPERTY_DECL( Props , float , PileupReweight )
PROPERTY_DECL( Props , unsigned int , RandomRunNumber ) //needed by CP tools
PROPERTY_DECL( Props , float , CorrectedAvgMu )
PROPERTY_DECL( Props , float , CorrectedAndScaledAvgMu )
PROPERTY_DECL( Props , float , CorrectedMu )
PROPERTY_DECL( Props , float , CorrectedAndScaledMu )
PROPERTY_DECL( Props , float , RecomputePileupReweight )
PROPERTY_DECL( Props , unsigned int , RecomputeRandomRunNumber ) //needed by CP tools
PROPERTY_DECL( Props , float , RecomputeCorrectedAvgMu )
PROPERTY_DECL( Props , float , RecomputeCorrectedAndScaledAvgMu )
PROPERTY_DECL( Props , float , RecomputeCorrectedMu )
PROPERTY_DECL( Props , float , RecomputeCorrectedAndScaledMu )
PROPERTY_DECL( Props , float , Pileupweight ) // backward compatibility CxAOD30 and earlier
PROPERTY_DECL( Props , float , averageInteractionsPerCrossing ) // backward compatibility CxAOD30 and earlier
PROPERTY_DECL( Props , float , actualInteractionsPerCrossing )
PROPERTY_DECL( Props , float , LumiWeight )
PROPERTY_DECL( Props , float , NTruthJetWeight )
PROPERTY_DECL( Props , float , ZPV )
PROPERTY_DECL( Props , float , HTXS_Higgs_pt )
PROPERTY_DECL( Props , float , HTXS_Higgs_eta )
PROPERTY_DECL( Props , float , HTXS_Higgs_phi )
PROPERTY_DECL( Props , float , HTXS_Higgs_m )
PROPERTY_DECL( Props , float , HTXS_V_pt )
PROPERTY_DECL( Props , float , HTXS_V_eta )
PROPERTY_DECL( Props , float , HTXS_V_phi )
PROPERTY_DECL( Props , float , HTXS_V_m )
PROPERTY_DECL( Props , float , leptonSF )
PROPERTY_DECL( Props , float , TTLH_MMC )
PROPERTY_DECL( Props , float , TTLH_mT )
PROPERTY_DECL( Props , float , TTLH_mvis )
PROPERTY_DECL( Props , float , TTLH_drleptau )
PROPERTY_DECL( Props , float , TTLH_ptH )
PROPERTY_DECL( Props , float , TTLH_detajj )
PROPERTY_DECL( Props , float , TTLH_pttot )
PROPERTY_DECL( Props , float , TTLH_ptl_over_pttau )
PROPERTY_DECL( Props , float , TTLH_lep_eta_cent )
PROPERTY_DECL( Props , float , TTLH_met_phi_cent )
PROPERTY_DECL( Props , float , TTLH_sumpt )
PROPERTY_DECL( Props , float , TTLH_mjj )
PROPERTY_DECL( Props , float , TTLH_jet_cent )
PROPERTY_DECL( Props , float , TTLH_tau_x1 )
PROPERTY_DECL( Props , float , TTLH_lep_x2 )
PROPERTY_DECL( Props , float , TTLH_sumdphi )
PROPERTY_DECL( Props , float , TTLH_globalweight )
PROPERTY_DECL( Props , float , TTLH_btaggingweight )
PROPERTY_DECL( Props , int , HHbbtautauTrigger )

// trigger match flags for photons
PROPERTY_DECL( Props , int , matchHLT_g20_loose )
PROPERTY_DECL( Props , int , matchHLT_g15_loose_2j40_0eta490_3j25_0eta490)
PROPERTY_DECL( Props , int , matchHLT_g20_loose_2j40_0eta490_3j25_0eta490)
PROPERTY_DECL( Props , int , matchHLT_g20_loose_2j40_0eta490_3j25_0eta490_L1MJJ700)
PROPERTY_DECL( Props , int , matchHLT_g20_loose_2j40_0eta490_3j25_0eta490_L1MJJ900)
PROPERTY_DECL( Props , int , matchHLT_g20_loose_L1EM18VH_2j40_0eta490_3j25_0eta490_invm700)
PROPERTY_DECL( Props , int , matchHLT_g25_loose_L1EM20VH_2j40_0eta490_3j25_0eta490_invm700)
PROPERTY_DECL( Props , int , matchHLT_g25_loose_2j40_0eta490_3j25_0eta490_invm700)
PROPERTY_DECL( Props , int , matchHLT_g25_medium_L1EM22VHI_4j35_0eta490_invm700)
PROPERTY_DECL( Props , int , matchHLT_g25_medium_L1EM22VHI_4j35_0eta490_invm1000)
PROPERTY_DECL( Props , int , matchPhHLT_g25_medium_L1EM22VHI_j35_0eta490_bmv2c2077_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , matchPhHLT_g25_medium_L1EM22VHI_2j35_0eta490_bmv2c2077_2j35_0eta490)
PROPERTY_DECL( Props , int , matchPhHLT_g25_medium_L1EM22VHI_j35_0eta490_bmv2c2077_split_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , matchPhHLT_g25_medium_L1EM22VHI_2j35_0eta490_bmv2c2077_split_2j35_0eta490)
PROPERTY_DECL( Props , int , matchPhHLT_g25_medium_L1EM22VHI_j35_0eta490_bmv2c1077_split_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , matchPhHLT_g25_medium_L1EM22VHI_2j35_0eta490_bmv2c1077_split_2j35_0eta490)
PROPERTY_DECL( Props , int , matchPhHLT_g20_tight_icaloloose_j15_gsc35_bmv2c1077_split_3j35_0eta490_invm500)
PROPERTY_DECL( Props , int , matchPhHLT_g20_tight_icaloloose_j35_bmv2c1077_split_3j35_0eta490_invm500)
PROPERTY_DECL( Props , int , matchHLT_g25_loose_L1EM20VH_4j35_0eta490)
PROPERTY_DECL( Props , int , matchHLT_g140_loose )

// trigger matching flags for b-jets
PROPERTY_DECL( Props , int , matchBJetHLT_g25_medium_L1EM22VHI_j35_0eta490_bmv2c2077_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , matchBJetHLT_g25_medium_L1EM22VHI_2j35_0eta490_bmv2c2077_2j35_0eta490)
PROPERTY_DECL( Props , int , matchBJetHLT_g25_medium_L1EM22VHI_j35_0eta490_bmv2c2077_split_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , matchBJetHLT_g25_medium_L1EM22VHI_2j35_0eta490_bmv2c2077_split_2j35_0eta490)
PROPERTY_DECL( Props , int , matchBJetHLT_g25_medium_L1EM22VHI_j35_0eta490_bmv2c1077_split_3j35_0eta490_invm700)
PROPERTY_DECL( Props , int , matchBJetHLT_g25_medium_L1EM22VHI_2j35_0eta490_bmv2c1077_split_2j35_0eta490)
PROPERTY_DECL( Props , int , matchBJetHLT_g20_tight_icaloloose_j15_gsc35_bmv2c1077_split_3j35_0eta490_invm500)
PROPERTY_DECL( Props , int , matchBJetHLT_g20_tight_icaloloose_j35_bmv2c1077_split_3j35_0eta490_invm500)


// trigger match flags for leptons - electrons commented out until validated
PROPERTY_DECL( Props , int , matchHLT_mu26_imedium )
PROPERTY_DECL( Props , int , matchHLT_mu14 )
PROPERTY_DECL( Props , int , matchHLT_mu20_iloose_L1MU15 )
PROPERTY_DECL( Props , int , matchHLT_mu24_iloose_L1MU15 )
PROPERTY_DECL( Props , int , matchHLT_mu24_imedium )
PROPERTY_DECL( Props , int , matchHLT_mu40 )
PROPERTY_DECL( Props , int , matchHLT_mu50 )
PROPERTY_DECL( Props , int , matchHLT_mu50_0eta105_msonly )
PROPERTY_DECL( Props , int , matchHLT_mu60 )
PROPERTY_DECL( Props , int , matchHLT_mu60_0eta105_msonly )
PROPERTY_DECL( Props , int , matchHLT_mu80 )
PROPERTY_DECL( Props , int , matchHLT_mu28_ivarmedium)
PROPERTY_DECL( Props , int , matchHLT_mu26_ivarmedium)
PROPERTY_DECL( Props , int , matchHLT_mu24_ivarmedium )
PROPERTY_DECL( Props , int , matchHLT_mu24_ivarloose )
PROPERTY_DECL( Props , int , matchHLT_mu24_ivarloose_L1MU15 )
PROPERTY_DECL( Props , int , matchHLT_mu24_iloose )
PROPERTY_DECL( Props , int , matchHLT_mu18_mu8noL1 )
PROPERTY_DECL( Props , int , matchHLT_mu22_mu8noL1 )
PROPERTY_DECL( Props , int , matchHLT_2mu14 )
PROPERTY_DECL( Props , int , matchHLT_e26_tight_iloose )
PROPERTY_DECL( Props , int , matchHLT_e26_tight1_iloose )
PROPERTY_DECL( Props , int , matchHLT_e26_lhtight_iloose )
PROPERTY_DECL( Props , int , matchHLT_e60_medium )
PROPERTY_DECL( Props , int , matchHLT_e60_medium1 )
PROPERTY_DECL( Props , int , matchHLT_e60_lhmedium )
PROPERTY_DECL( Props , int , matchHLT_e120_lhloose )
PROPERTY_DECL( Props , int , matchHLT_e140_lhloose )
PROPERTY_DECL( Props , int , matchHLT_e17_lhloose_L1EM15 )
PROPERTY_DECL( Props , int , matchHLT_e24_lhvloose_L1EM18VH )
PROPERTY_DECL( Props , int , matchHLT_e24_lhvloose_L1EM20VH )
PROPERTY_DECL( Props , int , matchHLT_e24_lhmedium_iloose_L1EM18VH )
PROPERTY_DECL( Props , int , matchHLT_e24_lhmedium_iloose_L1EM20VH )
PROPERTY_DECL( Props , int , matchHLT_e24_lhmedium_L1EM18VH )
PROPERTY_DECL( Props , int , matchHLT_e24_lhmedium_L1EM20VH )
PROPERTY_DECL( Props , int , matchHLT_e24_medium_iloose_L1EM18VH )
PROPERTY_DECL( Props , int , matchHLT_e24_medium_iloose_L1EM20VH )
PROPERTY_DECL( Props , int , matchHLT_e24_tight_iloose )
PROPERTY_DECL( Props , int , matchHLT_e24_lhtight_iloose )
PROPERTY_DECL( Props , int , matchHLT_e26_lhtight_ivarloose )
PROPERTY_DECL( Props , int , matchHLT_e24_lhtight_ivarloose )
PROPERTY_DECL( Props , int , matchHLT_e24_lhtight_nod0_ivarloose )
PROPERTY_DECL( Props , int , matchHLT_e24_lhmedium_ivarloose )
PROPERTY_DECL( Props , int , matchHLT_e24_lhmedium_nod0_ivarloose )
PROPERTY_DECL( Props , int , matchHLT_e24_lhmedium_nod0_L1EM20VH )
PROPERTY_DECL( Props , int , matchHLT_e26_lhtight_nod0_ivarloose )
PROPERTY_DECL( Props , int , matchHLT_e26_lhtight_nod0 )
PROPERTY_DECL( Props , int , matchHLT_e26_lhtight_smooth_ivarloose )
PROPERTY_DECL( Props , int , matchHLT_e26_lhmedium_nod0_ivarloose )
PROPERTY_DECL( Props , int , matchHLT_e60_lhmedium_nod0 )
PROPERTY_DECL( Props , int , matchHLT_e80_lhmedium_nod0 )
PROPERTY_DECL( Props , int , matchHLT_e120_lhloose_nod0 )
PROPERTY_DECL( Props , int , matchHLT_e140_lhloose_nod0 )
PROPERTY_DECL( Props , int , matchHLT_e300_etcut )
PROPERTY_DECL( Props , int , matchHLT_2e12_lhloose_L12EM10VH )
PROPERTY_DECL( Props , int , matchHLT_2e17_lhvloose_nod0 )
PROPERTY_DECL( Props , int , matchHLT_2e17_lhvloose_nod0_L12EM15VHI )
PROPERTY_DECL( Props , int , matchHLT_2e24_lhvloose_nod0 )
PROPERTY_DECL( Props , int , matchHLT_e17_lhloose_mu14 )
PROPERTY_DECL( Props , int , matchHLT_e17_lhloose_nod0_mu14 )
PROPERTY_DECL( Props , int , matchHLT_e26_lhmedium_nod0_mu8noL1 )
PROPERTY_DECL( Props , int , matchHLT_e26_lhmedium_nod0_L1EM22VHI_mu8noL1 )
PROPERTY_DECL( Props , int , matchHLT_e7_lhmedium_mu24 )
PROPERTY_DECL( Props , int , matchHLT_e7_lhmedium_nod0_mu24 )

// trigger match flags for taus
PROPERTY_DECL( Props , int , matchHLT_tau35_loose1_tracktwo_tau25_loose1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_tau35_loose1_tracktwo_tau25_loose1_tracktwo_L1TAU20IM_2TAU12IM)
PROPERTY_DECL( Props , int , matchHLT_tau40_medium1_tracktwoEF_tau35_medium1_tracktwoEF)
PROPERTY_DECL( Props , int , matchHLT_tau40_mediumRNN_tracktwoMVA_tau35_mediumRNN_tracktwoMVA )
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_L1TAU20IM_2TAU12IM)
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_L1TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int , matchHLT_tau80_medium1_tracktwo )
PROPERTY_DECL( Props , int , matchHLT_tau25_medium1_tracktwo )
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwo )
PROPERTY_DECL( Props , int , matchHLT_tau80_medium1_tracktwo_L1TAU60 )
PROPERTY_DECL( Props , int , matchHLT_tau125_medium1_tracktwo )
PROPERTY_DECL( Props , int , matchHLT_tau160_medium1_tracktwo )
PROPERTY_DECL( Props , int , matchHLT_tau160_medium1_tracktwoEF_L1TAU100 )
PROPERTY_DECL( Props , int , matchHLT_tau160_medium1_tracktwo_L1TAU100 )
PROPERTY_DECL( Props , int , matchHLT_tau160_mediumRNN_tracktwoMVA_L1TAU100 )
PROPERTY_DECL( Props , int , matchHLT_tau80_medium1_tracktwo_L1TAU60_tau50_medium1_tracktwo_L1TAU12)
PROPERTY_DECL( Props , int , matchHLT_tau80_medium1_tracktwo_L1TAU60_tau35_medium1_tracktwo_L1TAU12IM_L1TAU60_DR_TAU20ITAU12I)
PROPERTY_DECL( Props , int , matchHLT_tau80_medium1_tracktwo_L1TAU60_tau60_medium1_tracktwo_L1TAU40)
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_03dR30_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwoEF_tau25_medium1_tracktwoEF_03dR30_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int , matchHLT_tau35_mediumRNN_tracktwoMVA_tau25_mediumRNN_tracktwoMVA_03dR30_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwoEF_tau25_medium1_tracktwoEF_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int , matchHLT_tau35_mediumRNN_tracktwoMVA_tau25_mediumRNN_tracktwoMVA_L1DR_TAU20ITAU12I_J25)
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwo_tau25_medium1_tracktwo_L1TAU20IM_2TAU12IM_4J12)
PROPERTY_DECL( Props , int , matchHLT_tau35_medium1_tracktwoEF_tau25_medium1_tracktwoEF_L1TAU20IM_2TAU12IM_4J12_0ETA23)
PROPERTY_DECL( Props , int , matchHLT_tau35_mediumRNN_tracktwoMVA_tau25_mediumRNN_tracktwoMVA_L1TAU20IM_2TAU12IM_4J12_0ETA23)
PROPERTY_DECL( Props , int , matchHLT_tau80_medium1_TAU60_tau50_medium1_L1TAU12)
PROPERTY_DECL( Props , int , matchHLT_tau80_medium1_tracktwoEF_L1TAU60_tau35_medium1_tracktwoEF_L1TAU12IM_L1TAU60_DR_TAU20ITAU12I)
PROPERTY_DECL( Props , int , matchHLT_tau40_medium1_tracktwo_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_tau80_medium1_tracktwoEF_L1TAU60_tau60_medium1_tracktwoEF_L1TAU40)
PROPERTY_DECL( Props , int , matchHLT_tau80_mediumRNN_tracktwoMVA_L1TAU60_tau35_mediumRNN_tracktwoMVA_L1TAU12IM_L1TAU60_DR_TAU20ITAU12I)
PROPERTY_DECL( Props , int , matchHLT_tau80_mediumRNN_tracktwoMVA_L1TAU60_tau60_mediumRNN_tracktwoMVA_L1TAU40)

PROPERTY_DECL( Props , int , matchHLT_e17_lhmedium_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_e17_lhmedium_nod0_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_e17_lhmedium_iloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,matchHLT_e17_medium_iloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int ,matchHLT_e17_medium_tau80_medium1_tracktwo)
PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwo_L1DR_EM15TAU12I_J25)
PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_ivarloose_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_iloose_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwo_L1EM15VHI_2TAU12IM_4J12)
PROPERTY_DECL( Props , int ,matchHLT_e24_lhmedium_nod0_ivarloose_tau35_medium1_tracktwo)
//
PROPERTY_DECL( Props , int , matchHLT_mu14_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_mu14_ivarloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_mu14_iloose_tau25_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_mu14_iloose_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_mu14_tau35_medium1_tracktwo_L1TAU20)
PROPERTY_DECL( Props , int , matchHLT_mu14_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_mu14_ivarloose_tau25_medium1_tracktwo_L1DR_MU10TAU12I_TAU12I_J25)
PROPERTY_DECL( Props , int , matchHLT_mu14_ivarloose_tau35_medium1_tracktwo_L1MU10_TAU20IM_J25_2J20)
PROPERTY_DECL( Props , int , matchHLT_mu14_ivarloose_tau35_medium1_tracktwo)
PROPERTY_DECL( Props , int , matchHLT_mu14_ivarloose_tau25_medium1_tracktwo_L1MU10_TAU12IM_3J12)

// 2018 leptau
PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwoEF)
PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_ivarloose_tau25_mediumRNN_tracktwoMVA)

// backup
PROPERTY_DECL( Props , int ,matchHLT_e24_lhmedium_nod0_ivarloose_tau35_medium1_tracktwoEF)
PROPERTY_DECL( Props , int ,matchHLT_e24_lhmedium_nod0_ivarloose_tau35_mediumRNN_tracktwoMVA)

PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwoEF_L1DR_EM15TAU12I_J25)
PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_ivarloose_tau25_mediumRNN_tracktwoMVA_L1DR_EM15TAU12I_J25)

PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_ivarloose_tau25_medium1_tracktwoEF_L1EM15VHI_2TAU12IM_4J12)
PROPERTY_DECL( Props , int ,matchHLT_e17_lhmedium_nod0_ivarloose_tau25_mediumRNN_tracktwoMVA_L1EM15VHI_2TAU12IM_4J12)

PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau35_medium1_tracktwoEF)
PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau35_mediumRNN_tracktwoMVA)

PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau25_medium1_tracktwoEF)
PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau25_mediumRNN_tracktwoMVA)

// backup
PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau35_medium1_tracktwoEF_L1MU10_TAU20IM_J25_2J20)
PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau35_mediumRNN_tracktwoMVA_L1MU10_TAU20IM_J25_2J20)

PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau25_medium1_tracktwoEF_L1DR_MU10TAU12I_TAU12I_J25)
PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau25_mediumRNN_tracktwoMVA_L1DR_MU10TAU12I_TAU12I_J25)

PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau25_medium1_tracktwoEF_L1MU10_TAU12IM_3J12)
PROPERTY_DECL( Props , int ,matchHLT_mu14_ivarloose_tau25_mediumRNN_tracktwoMVA_L1MU10_TAU12IM_3J12)


PROPERTY_DECL( Props , float , ptvarcone20 )
PROPERTY_DECL( Props , float , ptvarcone20_TightTTVA_pt1000 )
PROPERTY_DECL( Props , float , ptvarcone30 )
PROPERTY_DECL( Props , float , ptvarcone30_TightTTVA_pt1000 )
PROPERTY_DECL( Props , float , topoetcone20 )
PROPERTY_DECL( Props , float , topoetcone30 )
PROPERTY_DECL( Props , float , topoetcone40 )
PROPERTY_DECL( Props , float , ptcone20 )
PROPERTY_DECL( Props , float , ptcone30 )
PROPERTY_DECL( Props , float , ptcone40 )
PROPERTY_DECL( Props , float , ptvarcone40 )
PROPERTY_DECL( Props , int , fatJetFlav )

#endif // __MAKECINT__
#endif //CxAODMaker_CommonProperties_H
