#!/bin/bash

# Script for creating a .cxx file corresponding to .h file containing "PROPERTY_DECL" declarations

package=CxAODTools
file=CommonProperties

if [ -n "$1" ]; then package=$1; fi
if [ -n "$2" ]; then file=$2; fi

hFile=$package/$package/$file.h
cFile=$package/Root/$file.cxx

if [ -e $hFile ]; then
  echo "Info: createPropsCXX.sh creating $hFile -> $cFile"
  echo -e '\n// This file was automatically generated by CxAODTools/scripts/createPropsCXX.sh\n' > $cFile.tmp
  echo '#include "'$package/$file'.h"' >> $cFile.tmp
  cat $hFile | grep "PROPERTY_DECL" | sed s/"PROPERTY_DECL"/"PROPERTY_INST"/g >> $cFile.tmp
  dif="<cxx file not present>"
  if [ -e $cFile ]; then
    dif=$(diff $cFile.tmp $cFile)
  fi
  if [ -n "$dif" ]; then
    mv $cFile.tmp $cFile
    echo "Info: $cFile updated."
  else
    rm $cFile.tmp
    echo "Info: $cFile already up to date."
  fi
else
  echo "Error: $hFile not found!"
fi
